### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Firegarden** [WhichBrowser/Parser-PHP#103]
We like this library but it feels too complicated to get started. Is there simple instructions where I can download the source code without figuring out how to use composer? 

It is a limited point of view to only offer installation instructions via composer and not a fall back set of instructions to download it and just use it.

**Comment by Firegarden** [comment]
I have come to figure out how to install composer and so I am giving this a go. It would be easier if the instructions were available to use without the dependency on composer but I understand having composer itself makes it easier to install this as a packaged bundle.

**Comment by NielsLeenheer** [comment]
Composer is nowadays the way to use external dependencies like libraries. Standalone use of this library is not supported, because it would complicate things quite a bit, because how to use it standalone is dependant on how your project looks like. With composer it is just a simple install command and use the classes you need. Much simpler.
