### ISSUE TITLE
Problem with Slackbot-LinkExpanding

### ISSUE THREAD

**Issue by hpawe01** [WhichBrowser/Parser-PHP#125]
The slackbot has the user-agent `Slackbot-LinkExpanding 1.0 (+https://api.slack.com/robots)`.
This results in a browser, that does not contain any name (not even an empty one).
In my understanding, the `browser` property should **always** have the `name` property.

```php
$client = new Parser('Slackbot-LinkExpanding 1.0 (+https://api.slack.com/robots)');
$name = $client->browser->name
\\ Undefined property: WhichBrowser\Model\Browser::$name
```

Result of `dd($client->browser)` (Laravel)
````
WhichBrowser\Model\Browser {#234 ▼
  +stock: true
  +hidden: false
  +mode: ""
  +type: ""
}
```

**Comment by mariotsi** [comment]
No, it's not guaranteed to be there if the browser is not completely detected. Use `getName()` on the browser object if you want to access `name` safely (but it also does some more things https://github.com/WhichBrowser/Parser-PHP/blob/3810e9aceed8acab7f27d1145579cae30eb59ac0/src/Model/Browser.php#L66 ).

However, in order to get the correct name @NielsLeenheer needs to add the definition for it.

**Comment by hpawe01** [comment]
All right, thanks @mariotsi ! I did not now about the getter because in the `README.md` only the direct access of the property is mentioned.
